{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 120,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n",
      "/home/sgillen/work/external/rl-baselines3-zoo/rl-trained-agents/ppo/HalfCheetahBulletEnv-v0_1/HalfCheetahBulletEnv-v0\n",
      "Loading running average\n",
      "with params: {'norm_obs': True, 'norm_reward': True}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: \u001b[33mWARN: Box bound precision lowered by casting to float32\u001b[0m\n",
      "  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))\n"
     ]
    }
   ],
   "source": [
    "import pybullet_envs\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import os\n",
    "import pickle\n",
    "import xarray as xr\n",
    "import matplotlib.pyplot as plt\n",
    "import copy\n",
    "import pybullet_envs\n",
    "import panda_gym\n",
    "\n",
    "from seagul.rl.ars.ars_zoo import ARSZooAgent\n",
    "from seagul.mesh import mdim_div_stable, mesh_dim, mesh_find_target_d\n",
    "from seagul.zoo3_utils import do_rollout_stable, load_zoo_agent\n",
    "\n",
    "torch.set_default_dtype(torch.float32)\n",
    "\n",
    "\n",
    "%matplotlib inline\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "env_name = 'HalfCheetahBulletEnv-v0'\n",
    "algo = 'ppo'\n",
    "\n",
    "#env_name = 'PandaReach-v1'\n",
    "#algo = 'tqc'\n",
    "\n",
    "env, model = load_zoo_agent(env_name, algo)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 112,
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-112-36bf13e2676f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mdes_list\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mthing\u001b[0m \u001b[0;32min\u001b[0m \u001b[0modict\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m     \u001b[0mo_list\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mthing\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'observation'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m     \u001b[0mach_list\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mthing\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'achieved_goal'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m     \u001b[0mdes_list\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mthing\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'desired_goal'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mIndexError\u001b[0m: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices"
     ]
    }
   ],
   "source": [
    "odict,a,r,i = do_rollout_stable(env, model);\n",
    "o_list = []\n",
    "ach_list = []\n",
    "des_list = []\n",
    "for thing in odict:\n",
    "    o_list.append(thing['observation'])\n",
    "    ach_list.append(thing['achieved_goal'])\n",
    "    des_list.append(thing['desired_goal'])\n",
    "    \n",
    "o = np.stack(o_list).squeeze()\n",
    "ach = np.stack(ach_list).squeeze()\n",
    "des = np.stack(des_list).squeeze()\n",
    "\n",
    "\n",
    "plt.plot(o);\n",
    "plt.figure()\n",
    "\n",
    "plt.plot(ach);\n",
    "plt.plot(des);"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "ename": "UnboundLocalError",
     "evalue": "local variable 'lin_end' referenced before assignment",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnboundLocalError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-39-92347b78b97e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mmdim\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcdim\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mm\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0md\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmesh_dim\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mo\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m200\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mupper_size_ratio\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1.0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlower_size_ratio\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0.0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mdcrit\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmesh_find_target_d\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mo\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mloglog\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0md\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mm\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m'x-'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mxlabel\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'd'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/work/seagul/seagul/mesh.py\u001b[0m in \u001b[0;36mmesh_dim\u001b[0;34m(data, scaling_factor, init_d, upper_size_ratio, lower_size_ratio, d_limit)\u001b[0m\n\u001b[1;32m    190\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    191\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 192\u001b[0;31m     \u001b[0mxdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlog2\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0md_vals\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mlin_begin\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0mlin_end\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    193\u001b[0m     \u001b[0mydata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlog2\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmesh_sizes\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mlin_begin\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0mlin_end\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    194\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mUnboundLocalError\u001b[0m: local variable 'lin_end' referenced before assignment"
     ]
    }
   ],
   "source": [
    "#mdim, cdim, m,d = mesh_dim(o[200:], upper_size_ratio=1.0, lower_size_ratio=0.0)\n",
    "#dcrit = mesh_find_target_d(o)\n",
    "\n",
    "plt.loglog(d,m,'x-')\n",
    "plt.xlabel('d')\n",
    "plt.ylabel('m')\n",
    "\n",
    "print(mdim)\n",
    "print(cdim)\n",
    "print(dcrit)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: \u001b[33mWARN: Box bound precision lowered by casting to float32\u001b[0m\n",
      "  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))\n"
     ]
    }
   ],
   "source": [
    "new_agent = ARSZooAgent(env_name, algo, seed=0, n_workers=8, n_delta=64, postprocessor=mdim_div_stable, step_schedule=[0.05, 0.005],  exp_schedule=[0.05, 0.005])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "env, old_model = load_zoo_agent(env_name, algo)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'new_agent' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-18-0b46e9b2b11e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mnew_agent\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlearn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m50\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m;\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mplot\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnew_agent\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mraw_rew_hist\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'new_agent' is not defined"
     ]
    }
   ],
   "source": [
    "new_agent.learn(50);\n",
    "plt.plot(new_agent.raw_rew_hist)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "mesh dimension\n",
      "[1.65165222 1.50077426 1.47188814 1.43729194 1.4891903  1.51134688\n",
      " 1.55907226 1.51392266 1.69615533 1.54201792]\n",
      "mean: 1.537331191504856, std: 0.07612935573121957\n",
      "rewards\n",
      "[27.29775238 26.79888535 26.62466812 26.59468842 26.71964455 27.29981232\n",
      " 27.79039383 27.31723595 27.36193085 27.00781059]\n",
      "mean: 27.081282234191896, std: 0.37324116445731953\n",
      "\n",
      "\n",
      "mesh dimension\n",
      "[1.04105945 1.12599638 1.17756477 1.1979042  1.0433496  1.21110457\n",
      " 1.03676292 1.09788625 1.22385127 1.1741975 ]\n",
      "mean: 1.132967691385411, std: 0.07020251916917747\n",
      "rewards\n",
      "[22.59495735 23.33088684 23.11067581 23.89262772 21.7189064  23.01237869\n",
      " 22.86103821 22.09728622 23.60745621 22.56051445]\n",
      "mean: 22.878672790527343, std: 0.6303239861898635\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "model_list = [old_model, new_agent.model]\n",
    "num_runs = 10\n",
    "\n",
    "for model in model_list:\n",
    "    mdims = xr.DataArray(np.zeros((num_runs)))\n",
    "    rews =  xr.DataArray(np.zeros((num_runs)))\n",
    "\n",
    "    for j in range(num_runs):\n",
    "        o,a,r,l = do_rollout_stable(env, model)\n",
    "        o_norm = env.normalize_obs(o).squeeze()\n",
    "        o_norm  = o_norm[200:]\n",
    "        rews[j] = np.sum(r)\n",
    "        try:\n",
    "            mdims[j], _, _, _ = mesh_dim(o_norm)\n",
    "        except:\n",
    "            mdims[j] = np.nan\n",
    "    print(\"mesh dimension\")\n",
    "    print(mdims.data)\n",
    "    mean = mdims.mean().item()\n",
    "    std = mdims.std().item()\n",
    "    print(f\"mean: {mean}, std: {std}\")\n",
    "\n",
    "    print(\"rewards\")\n",
    "    print(rews.data)\n",
    "    mean = rews.mean().item()\n",
    "    std = rews.std().item()\n",
    "    print(f\"mean: {mean}, std: {std}\")\n",
    "    print();print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-08-29 02:20:20,584\tINFO services.py:1269 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "2021-08-29 02:20:22,149\tWARNING function_runner.py:545 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.\n",
      "2021-08-29 02:20:22,174\tWARNING tune.py:494 -- Tune detects GPUs, but no trials are using GPUs. To enable trials to use GPUs, set tune.run(resources_per_trial={'gpu': 1}...) which allows Tune to expose 1 GPU to each trial. You can also override `Trainable.default_resource_request` if using the Trainable API.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 19.1/62.9 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 1.0/24 CPUs, 0/1 GPUs, 0.0/27.86 GiB heap, 0.0/13.93 GiB objects (0.0/1.0 accelerator_type:RTX)<br>Result logdir: /home/sgillen/ray_results/training_function_2021-08-29_02-20-22<br>Number of trials: 12/12 (11 PENDING, 1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                   </th><th>status  </th><th>loc  </th><th>algo  </th><th>env_name               </th><th>train  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>training_function_55f9f_00000</td><td>RUNNING </td><td>     </td><td>ppo   </td><td>Walker2DBulletEnv-v0   </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00001</td><td>PENDING </td><td>     </td><td>a2c   </td><td>Walker2DBulletEnv-v0   </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00002</td><td>PENDING </td><td>     </td><td>ppo   </td><td>HalfCheetahBulletEnv-v0</td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00003</td><td>PENDING </td><td>     </td><td>a2c   </td><td>HalfCheetahBulletEnv-v0</td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00004</td><td>PENDING </td><td>     </td><td>ppo   </td><td>HopperBulletEnv-v0     </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00005</td><td>PENDING </td><td>     </td><td>a2c   </td><td>HopperBulletEnv-v0     </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00006</td><td>PENDING </td><td>     </td><td>ppo   </td><td>Walker2DBulletEnv-v0   </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00007</td><td>PENDING </td><td>     </td><td>a2c   </td><td>Walker2DBulletEnv-v0   </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00008</td><td>PENDING </td><td>     </td><td>ppo   </td><td>HalfCheetahBulletEnv-v0</td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00009</td><td>PENDING </td><td>     </td><td>a2c   </td><td>HalfCheetahBulletEnv-v0</td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00010</td><td>PENDING </td><td>     </td><td>ppo   </td><td>HopperBulletEnv-v0     </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00011</td><td>PENDING </td><td>     </td><td>a2c   </td><td>HopperBulletEnv-v0     </td><td>True   </td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m 2021-08-29 02:20:22,693\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m 2021-08-29 02:20:22,720\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m 2021-08-29 02:20:22,736\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m 2021-08-29 02:20:22,789\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m 2021-08-29 02:20:22,739\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m 2021-08-29 02:20:22,756\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m 2021-08-29 02:20:22,766\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m 2021-08-29 02:20:22,788\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m 2021-08-29 02:20:22,791\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m 2021-08-29 02:20:22,802\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m 2021-08-29 02:20:22,829\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m 2021-08-29 02:20:22,813\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m \n",
      "2021-08-29 02:20:22,869\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13558, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13558, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,894\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00008: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13557, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13557, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,907\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00004: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13554, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13554, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,914\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00006: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13582, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13582, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,934\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00002: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13552, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13552, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,937\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00005: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13549, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13549, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,942\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00007: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13586, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13586, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,961\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00001: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13556, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13556, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,964\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00010: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13559, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13559, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,967\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00011: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13547, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13547, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,992\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00003: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13553, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13553, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:23,002\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00009: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13555, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13555, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for training_function_55f9f_00000:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00008:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00004:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00006:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00002:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00005:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00007:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00001:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00010:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00011:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00003:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00009:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 19.5/62.9 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 0/24 CPUs, 0/1 GPUs, 0.0/27.86 GiB heap, 0.0/13.93 GiB objects (0.0/1.0 accelerator_type:RTX)<br>Result logdir: /home/sgillen/ray_results/training_function_2021-08-29_02-20-22<br>Number of trials: 12/12 (12 ERROR)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                   </th><th>status  </th><th>loc  </th><th>algo  </th><th>env_name               </th><th>train  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>training_function_55f9f_00000</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>Walker2DBulletEnv-v0   </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00001</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>Walker2DBulletEnv-v0   </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00002</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>HalfCheetahBulletEnv-v0</td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00003</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>HalfCheetahBulletEnv-v0</td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00004</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>HopperBulletEnv-v0     </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00005</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>HopperBulletEnv-v0     </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00006</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>Walker2DBulletEnv-v0   </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00007</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>Walker2DBulletEnv-v0   </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00008</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>HalfCheetahBulletEnv-v0</td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00009</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>HalfCheetahBulletEnv-v0</td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00010</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>HopperBulletEnv-v0     </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00011</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>HopperBulletEnv-v0     </td><td>True   </td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 12<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                   </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                                         </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>training_function_55f9f_00000</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00000_0_algo=ppo,env_name=Walker2DBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt   </td></tr>\n",
       "<tr><td>training_function_55f9f_00001</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00001_1_algo=a2c,env_name=Walker2DBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt   </td></tr>\n",
       "<tr><td>training_function_55f9f_00002</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00002_2_algo=ppo,env_name=HalfCheetahBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt</td></tr>\n",
       "<tr><td>training_function_55f9f_00003</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00003_3_algo=a2c,env_name=HalfCheetahBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt</td></tr>\n",
       "<tr><td>training_function_55f9f_00004</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00004_4_algo=ppo,env_name=HopperBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt     </td></tr>\n",
       "<tr><td>training_function_55f9f_00005</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00005_5_algo=a2c,env_name=HopperBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt     </td></tr>\n",
       "<tr><td>training_function_55f9f_00006</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00006_6_algo=ppo,env_name=Walker2DBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt    </td></tr>\n",
       "<tr><td>training_function_55f9f_00007</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00007_7_algo=a2c,env_name=Walker2DBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt    </td></tr>\n",
       "<tr><td>training_function_55f9f_00008</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00008_8_algo=ppo,env_name=HalfCheetahBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt </td></tr>\n",
       "<tr><td>training_function_55f9f_00009</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00009_9_algo=a2c,env_name=HalfCheetahBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt </td></tr>\n",
       "<tr><td>training_function_55f9f_00010</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00010_10_algo=ppo,env_name=HopperBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt     </td></tr>\n",
       "<tr><td>training_function_55f9f_00011</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00011_11_algo=a2c,env_name=HopperBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt     </td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [training_function_55f9f_00000, training_function_55f9f_00001, training_function_55f9f_00002, training_function_55f9f_00003, training_function_55f9f_00004, training_function_55f9f_00005, training_function_55f9f_00006, training_function_55f9f_00007, training_function_55f9f_00008, training_function_55f9f_00009, training_function_55f9f_00010, training_function_55f9f_00011])",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-761a5f48f0d3>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     29\u001b[0m         \u001b[0;34m\"train\"\u001b[0m \u001b[0;34m:\u001b[0m \u001b[0mtune\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgrid_search\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     30\u001b[0m         \u001b[0;34m\"env_name\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mtune\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgrid_search\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Walker2DBulletEnv-v0\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\"HalfCheetahBulletEnv-v0\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\"HopperBulletEnv-v0\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 31\u001b[0;31m         \u001b[0;34m\"algo\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mtune\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgrid_search\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'ppo'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'a2c'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     32\u001b[0m     })\n\u001b[1;32m     33\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/tune.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, loggers, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint, _remote)\u001b[0m\n\u001b[1;32m    541\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    542\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mstate\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0msignal\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSIGINT\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 543\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    544\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    545\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete: %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTuneError\u001b[0m: ('Trials did not complete', [training_function_55f9f_00000, training_function_55f9f_00001, training_function_55f9f_00002, training_function_55f9f_00003, training_function_55f9f_00004, training_function_55f9f_00005, training_function_55f9f_00006, training_function_55f9f_00007, training_function_55f9f_00008, training_function_55f9f_00009, training_function_55f9f_00010, training_function_55f9f_00011])"
     ]
    }
   ],
   "source": [
    "from ray import tune\n",
    "\n",
    "def training_function(config):\n",
    "    import pybullet_envs\n",
    "\n",
    "    train, env_name, algo = config[\"train\"], config[\"env_name\"], config[\"algo\"]\n",
    "    env, model = load_zoo_agent(env_name, algo)\n",
    "    \n",
    "    if train:\n",
    "        new_agent = ARSZooAgent(env_name, algo, n_workers=24, n_delta=64, postprocessor=mdim_div_stable, step_schedule=[0.05, 0.005],  exp_schedule=[0.05, 0.005])\n",
    "        new_agent.learn(100) \n",
    "    \n",
    "    o,a,r,l = do_rollout_stable(env, model)\n",
    "    o_norm = env.normalize_obs(o).squeeze()\n",
    "    o_norm  = o_norm[200:]\n",
    "    rew = np.sum(r)\n",
    "    \n",
    "    try:\n",
    "        mdim, _, _, _ = mesh_dim(o_norm)\n",
    "    except:\n",
    "        mdim = np.nan\n",
    "\n",
    "    tune.report(mdim=mdim, reward=rew)\n",
    "\n",
    "\n",
    "analysis = tune.run(\n",
    "    training_function,\n",
    "    config={\n",
    "        \"train\" : tune.grid_search([False, True]),\n",
    "        \"env_name\": tune.grid_search([\"Walker2DBulletEnv-v0\",\"HalfCheetahBulletEnv-v0\",\"HopperBulletEnv-v0\"]),\n",
    "        \"algo\": tune.grid_search(['ppo', 'a2c'])\n",
    "    })\n",
    "\n",
    "print(\"Best config: \", analysis.get_best_config(\n",
    "    metric=\"mdim\", mode=\"min\"))\n",
    "\n",
    "# Get a dataframe for analyzing trial results.\n",
    "df = analysis.results_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "rd = analysis.results_df.to_csv('test.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'trial_id,mdim,reward,time_this_iter_s,done,timesteps_total,episodes_total,training_iteration,experiment_id,date,timestamp,time_total_s,pid,hostname,node_ip,time_since_restore,timesteps_since_restore,iterations_since_restore,experiment_tag,config.train,config.env_name,config.algo\\n5f944_00000,1.662833423343824,33.140342712402344,1.1313729286193848,True,,,1,efd44a352c0e4c329aa167aeb426124a,2021-08-29_01-52-02,1630227122,1.1313729286193848,3989,sguc2,128.111.57.96,1.1313729286193848,0,1,\"0_algo=ppo,env_name=Walker2DBulletEnv-v0,train=False\",False,Walker2DBulletEnv-v0,ppo\\n5f944_00001,,3.2583043575286865,0.13784122467041016,True,,,1,f626496cbc8844ec83297e7b39a95d1b,2021-08-29_01-52-01,1630227121,0.13784122467041016,3986,sguc2,128.111.57.96,0.13784122467041016,0,1,\"1_algo=a2c,env_name=Walker2DBulletEnv-v0,train=False\",False,Walker2DBulletEnv-v0,a2c\\n5f944_00002,1.651652224696957,27.297752380371094,1.145392894744873,True,,,1,c68871ecf92c4a8d926fef7de6a7d408,2021-08-29_01-52-02,1630227122,1.145392894744873,3999,sguc2,128.111.57.96,1.145392894744873,0,1,\"2_algo=ppo,env_name=HalfCheetahBulletEnv-v0,train=False\",False,HalfCheetahBulletEnv-v0,ppo\\n5f944_00003,1.6107201530829376,32.872032165527344,1.1958355903625488,True,,,1,d8b65ed2a5d249bd8ac5a7118471d57f,2021-08-29_01-52-03,1630227123,1.1958355903625488,3984,sguc2,128.111.57.96,1.1958355903625488,0,1,\"3_algo=a2c,env_name=HalfCheetahBulletEnv-v0,train=False\",False,HalfCheetahBulletEnv-v0,a2c\\n5f944_00004,1.5108682475970283,30.000423431396484,0.9771959781646729,True,,,1,10e9a28b84ad4cea8744a0b0bb2d0758,2021-08-29_01-52-02,1630227122,0.9771959781646729,3997,sguc2,128.111.57.96,0.9771959781646729,0,1,\"4_algo=ppo,env_name=HopperBulletEnv-v0,train=False\",False,HopperBulletEnv-v0,ppo\\n5f944_00005,0.8398481810348197,23.638809204101562,0.9235587120056152,True,,,1,37f0e3ae20ef4c68b84df9611802b5c1,2021-08-29_01-52-02,1630227122,0.9235587120056152,3979,sguc2,128.111.57.96,0.9235587120056152,0,1,\"5_algo=a2c,env_name=HopperBulletEnv-v0,train=False\",False,HopperBulletEnv-v0,a2c\\n5f944_00006,1.662833423343824,33.140342712402344,1.162675380706787,True,,,1,7d57844cb49b43438030217ad0dc0276,2021-08-29_01-52-02,1630227122,1.162675380706787,3987,sguc2,128.111.57.96,1.162675380706787,0,1,\"6_algo=ppo,env_name=Walker2DBulletEnv-v0,train=True\",True,Walker2DBulletEnv-v0,ppo\\n5f944_00007,,3.2583043575286865,0.19421648979187012,True,,,1,a425d2c6a78e4b2ebcc3987cca149705,2021-08-29_01-52-01,1630227121,0.19421648979187012,3981,sguc2,128.111.57.96,0.19421648979187012,0,1,\"7_algo=a2c,env_name=Walker2DBulletEnv-v0,train=True\",True,Walker2DBulletEnv-v0,a2c\\n5f944_00008,1.651652224696957,27.297752380371094,1.1691322326660156,True,,,1,e0bc9d9944f442289f3b904523920443,2021-08-29_01-52-02,1630227122,1.1691322326660156,3973,sguc2,128.111.57.96,1.1691322326660156,0,1,\"8_algo=ppo,env_name=HalfCheetahBulletEnv-v0,train=True\",True,HalfCheetahBulletEnv-v0,ppo\\n5f944_00009,1.6107201530829376,32.872032165527344,1.1936323642730713,True,,,1,d949752656d44a75a72bccb0298910aa,2021-08-29_01-52-02,1630227122,1.1936323642730713,3983,sguc2,128.111.57.96,1.1936323642730713,0,1,\"9_algo=a2c,env_name=HalfCheetahBulletEnv-v0,train=True\",True,HalfCheetahBulletEnv-v0,a2c\\n5f944_00010,1.5108682475970283,30.000423431396484,1.0029053688049316,True,,,1,e7b6be7a761040c6a1e2470af1d09fab,2021-08-29_01-52-02,1630227122,1.0029053688049316,3970,sguc2,128.111.57.96,1.0029053688049316,0,1,\"10_algo=ppo,env_name=HopperBulletEnv-v0,train=True\",True,HopperBulletEnv-v0,ppo\\n5f944_00011,0.8398481810348197,23.638809204101562,0.9461500644683838,True,,,1,5eb8457380334476b5aa84cab4d7120a,2021-08-29_01-52-02,1630227122,0.9461500644683838,3982,sguc2,128.111.57.96,0.9461500644683838,0,1,\"11_algo=a2c,env_name=HopperBulletEnv-v0,train=True\",True,HopperBulletEnv-v0,a2c\\n'"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'df' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-00cf07b74dcd>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mdf\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m: name 'df' is not defined"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Mujoco 1.5",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
