{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n",
      "Loading running average\n",
      "with params: {'norm_obs': True, 'norm_reward': True}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: \u001b[33mWARN: Box bound precision lowered by casting to float32\u001b[0m\n",
      "  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))\n"
     ]
    }
   ],
   "source": [
    "import pybullet_envs\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import os\n",
    "import pickle\n",
    "import xarray as xr\n",
    "import matplotlib.pyplot as plt\n",
    "import copy\n",
    "import pybullet_envs\n",
    "import panda_gym\n",
    "\n",
    "from seagul.rl.ars.ars_zoo import ARSZooAgent\n",
    "from seagul.mesh import mdim_div_stable, mesh_dim, mesh_find_target_d\n",
    "from seagul.rollouts import do_rollout_stable\n",
    "from seagul.rollouts import load_zoo_agent\n",
    "\n",
    "\n",
    "torch.set_default_dtype(torch.float32)\n",
    "\n",
    "\n",
    "%matplotlib inline\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "#env_name = 'HalfCheetahBulletEnv-v0'\n",
    "env_name = 'PandaReach-v1'\n",
    "algo = 'tqc'\n",
    "\n",
    "env, model = load_zoo_agent(env_name, algo)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "odict,a,r,i = do_rollout_stable(env, model);\n",
    "'achieved_goal'\n",
    "\n",
    "#plt.plot(o);"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.1765057632828895\n",
      "7.994432511283337\n",
      "1.6645905376314194\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYUAAAENCAYAAADgwHn9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAipElEQVR4nO3de3RU5b3/8fc3d66BJFwCAUICco8NRC5pq9a2AipqFXsEtNa6pKjosl3tqZ7T82t/y3pq7fmdntOicqhaVETssdqC4KWtVqsBJAka7pdwDbckXAIhgZDJ8/sjyTQgCQnMZM9MPq+1snD2PDPzRbf5zH6++9nbnHOIiIgARHldgIiIhA6FgoiI+CkURETET6EgIiJ+CgUREfFTKIiIiJ9CQURE/BQKIiLiFzKhYGYjzGy+mb1mZvd5XY+ISEdkwVzRbGbPAzcApc650U22TwH+G4gGnnXOPdHkuSjgRefcHRd6/5SUFJeenh7wukVEIllBQUG5c67X+Z6LCfJnLwTmAS82bjCzaOAp4OtACbDGzJY65zaa2Y3AfcBLrXnz9PR08vPzA160iEgkM7PdzT0X1Okj59yHwJFzNo8HtjvndjjnaoAlwE0N45c656YCs4JZl4iInF+wjxTOpz+wt8njEmCCmV0N3ALEAyuae7GZzQZmAwwcODBoRYqIdERehMJ5Oef+BvytFeMWAAsAcnJydIlXEZEA8uLso33AgCaP0xq2iYiIx7wIhTXAUDMbbGZxwO3A0ra8gZlNM7MFFRUVbfrg+R8Uk1dcfta2vOJy5n9QfEljRUQiRVBDwcxeAVYCw8ysxMzucc7VAnOBd4BNwO+dcxva8r7OuWXOudmJiYltqicrLZG5i9f6f9nnFZczd/FastI+/z5tGRussAnGWK8/X0RCW7DPPprhnEt1zsU659Kcc881bF/hnLvMOZfpnHs8mDU0lZuZwryZ2dy3qJAHXi5k9osFfOeL6VTX+PjrpkO8t/kQ728u5f0tpdTU1jH7ygy++1IBDy9Zy3dfKuC+qzMwjNU7DrNm1xEKdh+hYPdROsdFM+elAl5etZt1JRUsWrWLOS8V0CUumrV7jrJ2z1EK9xylYPdREmKjmPNSAQs/3kn+riMszPvH2KKSY6zfV8GG/RVsOnCcnp1juW9RIa/l72V7aSWvFezlvkWF9Ooax87yk+wqP8nuwyfZc7iKvt0TuG9RIX9au4/9x6pZXrSf+18uJD25M0dP1lBRfYbK07UM69OVB14u5O/byqircwELxlAIURG5dEFdvBYsZjYNmDZkyJB7t23b1ubXf3P+Sj7Zde6Zsh1XbLSREBtNXHQUsdFRxMVEERttxEZHUVNbx54jVfTpHk/pidOM6Z9In+4JTcZFEdcwtuzEad7deIgvDOjBZyXHmDlhIKP7JZIQG02nuGg6xdb/bDl4nJ8t38QTt47hS0N7Ubj7KA+/+inzZmaTm5lyVm2N4dL43LmPRaTtzKzAOZdz3ufCMRQa5eTkuLYuXssrLuf+RYVMGd2XFesO8M9ThpGV1gPnwAHOuYY/Yd2+Y/znu1v5+qg+vLvhEA9/bSgjUruDgzoHdc5R5x/veL1wH28WHeCGrFS+kd0fMzAMrP6zDTAzDHi9sIQ/frqfGy/vxzfG9sc5R11dfQ11ztU/dvV1LP1sP+9sOMjkUX24bkxqQ62u/s+G/3yNNby94SB/3VTKV4b15poRvXHO4aur/3EOfA2P/76tjFU7jnDFoJ6MHdSTGl8dNbV1nPHVccbnqPHVcabh8bbSSkqOVtOnezwpXeM/N+4fj+u3Xaz4mPqgiY+JIj4mmriYKOKio6jx1bH3SBXpKV3Yd7SauddkcsvYNPp2T8DM/K+f/0ExWWmJZ4VFXnE5RSUVzLkq86zPastYkUjTUiiEzCmp7aHxW+bTd4wlNzOFG7/Qr9lvnXnF5fz6r9uZf+e4+m+oY5t8Qx3y+W+oecXl5BUf5qFrhrBo9R5mThjY7DfZvOJyPtxW7h97+/gBLY5ds+uIf+xduektjl2755h/7L1XDj7v2Lzicp77aKd/3PeuvazF95y7eK1/7L9eP+KCY2+/YgCvfLKHn908mpH9Eqmu8VF9xsepMz6qa3ycqq3/c3nRAf62tYxJGclckd6T0w0Bc7q2/s/6f/b5Q2d7aSUAv3xnK798Zys9O8cyIrU7I1O7MyK1O4kJsTzwciFPzRr7uaOKczVOd53vCORcChDpSDrUkUKwvkm2ZYrD67Fef/654++YMJBFq/e0OB3UdOxLq3bz0FeHEh1lbNx/nE0HjrP54AlO19YBEB0FYPTv0YkDFdVMGJzMgKTO9VNXcVF0io0moeFn39FqXlq1m2uG9+b9LaU8MmU4EzKS6RwX3fATQ1xMlKawJOJE3PTRpfYUAi1YYROMsV5/fuP2QIZNra+OneUn2XjgOBsPHOetdQfZc6SKpC6xdImPobqmjlNnfFTV1FLXxt09JsroFBdNTJRxvPoMYwf1ZNuhSv/Rpkg4irhQaHQxPQXxXjDn/ls6AnHOccbnOFXr41SNj4+Ly/nJ0g1MHtWXt9cfZPaVGQxM6kxVjY+qGh/VNbVN/tlH3o5y9h6pxoDrs1L5dm464wb1PKuvIRIOFArSIbTHdNe0rFReXbMXM6g+U8eoft35dm460y7vR0JsdHv9VUUuiUJBOoT2nO564OVCbhnbnw+3lrOttJKkLnEM69OVmRMGMe3yfhd8TxEvKRRELkFLAfLdKzNYWXyYhXm7+PPGQzhgwuCefO/rw/D5HA8uUUNaQk/EhUKoNZpFAPYeqeIXb29medEBHGAG1wzrzbdy05mUkUxcTMjc/VY6uIgLhUY6UpBQ9Iu3NvPMB8UM6d2F/cdOUVXjo1t8DFcP783kUX246rJevLx6j9Y+iGe0eE2kneQVl/Nq/l7/Yr+nZ43FV+d4d8Mh/rLpEMs+209cdBQj+nXj13/dxn/clsV1Y/q1uHhOpD0pFEQC5NyG9MTMZP/jX0zPwlfnKNxzlHfWH+TdjYeoqvFx/8trSU3cREX1GX45PUu9B/Gcpo9EAqQtZzQ559hy6AQ/+dMGVu+svzijGVwxKInrs1KZOrovvbsntGv90nFEXE9BjWaJBE0X2r2wcjfXjuzDun0VbD54AjMYn57EDVmplJ44zaTMZPUfJGAiLhQa6UhBwlVLi+d6dY1n+boDvFl0gO2llRgQHWXclTuI+68ewpZDJ3TtJbkkCgWRENPaqaath07wZtEB/jd/LwcqTgH112O6LSeNe76UQWavLrrMhrSZQkEkzDnn+Jc31vHKJ3vp1S2OshM1AAxO6cLXRvTmayP6MG5QT579aKdOdZULaikUtJpGJAys3HGYdzYc4qFrhuCrg9/MyOaxm0czMKkzL+Tt5p8WrCLn8b/w8bZyZr9YwHubDwEt3xZV5Hx0SqpIiGvpVNc7vzOeytO1/H1rGX/edIj3NpdSebqW7yzMJ6NXF8pPnPbfKEqkNRQKIiGuqKTirKZybmYK82ZmU1RSQW5mCl3jY5g6JpWpY1Kp9dVRuOcYP1+xibV7jwGw4MMdxMdEM25QTw//FhIuwrKnoFNSRZrXeGRx27g0Xly5m5ho48SpWnIzk3noq0OZmJHsdYnisYjrKTjnljnnZicmap5UpKmmU02PXjeC576dQ0yUMWvCQLYequT2Bav45vyVfLi1jGf+tp284vLPvX7+B8UeVS+hICxDQUTO73xTTU/NGsuApM589KOv8NNpI9lzpIpvPf8JrxWUMPvFAvK21weDmtICYTp91EinpIq03elaH68VlPDM34opOVpNdJTxjez+vLe5VAviOoiImz4SkYsXHxPNrAmDeP8HV/Pk9Cw6xUbxWkEJt41LUyCIQkGko4qNjiKtZyeiGlZEv5C363M9Bul4FAoiHVRjD2H+neOYNWEgp2vrmPNSgYKhg1MoiHRQTZvSP5w8jJ5d4uibmMBnDesbpGMKy1Aws2lmtqCiosLrUkTC1pyrMv09hB6d43h06nC2HqokuUu8x5WJl8IyFLROQSTwbh2bxhXpPfn5W5s4erLG63LEI2EZCiISeFFRxmM3j+b4qVqefGeL1+WIRxQKIuI3vG937s5NZ8maPazdc9TrcsQDCgUROcvDX7+M3t3i+fEf1+OrC9/FrXJxFAoicpau8TH82w0j2bD/OItW7fa6HGlnCgUR+Zzrx6Ty5aEp/Mc7Wyg9ccrrcqQdKRRE5HPMjP974yhO19bx8xWbvS5H2pFCQUTOK6NXV757VQZvrN3HyuLDXpcj7UShICLNeuArQxiQ1Il/+9N6amrrvC5H2oFCQUSalRAbzU+njWJ7aSXPf7zT63KkHSgURKRFXx3Rh6G9u/Kf725l37Fq/3bdpS0yhWUo6NpHIu3rwWuGUOOr4+ElawHdpS2S6c5rItIqP/pDEa+u2cuNl/fjo+3luktbGNOd10Tkkj1202g6x0Wz9LP93DFhoAIhQikURKRV8ncfodbn6BwXzaLVe3QzngilUBCRC2rsIdyVO4iqGh//MnU4cxevVTBEIIWCiFxQ413aZk0YBEB1bR3zZmZTVKKTPSJNjNcFiEjom3NVJgDOOVITE1i14zB3ThykvkIE0pGCiLSamTExI5nVOw4TzmcuSvMUCiLSJpMykimvrGF7aaXXpUgQKBREpE0mZiQDsHKHLpIXiRQKItImA5I60b9HJ1YpFCKSQkFE2sTMmJCRxKodR6jT7TojjkJBRNpsUkYyR07WsE19hYijUBCRNvP3FbR4LeIoFESkzQYkdSatZyc1myOQQkFELsqkjGRW71RfIdIoFETkokzMSOZY1Rk2HzzhdSkSQCEVCmZ2s5n91sxeNbNrva5HRJo3MbO+r6BTUyNL0EPBzJ43s1IzW3/O9ilmtsXMtpvZIwDOuT865+4F5gD/FOzaROTi9e/RiYFJndVXiDDtcaSwEJjSdIOZRQNPAVOBkcAMMxvZZMiPG54XkRA2KSOZT9RXiChBDwXn3IfAkXM2jwe2O+d2OOdqgCXATVbvF8BbzrnCYNcmIpdmYmYSFdVn2HjguNelSIB41VPoD+xt8rikYduDwNeA6WY253wvNLPZZpZvZvllZWXBr1REmtW4XkF9hcgRUo1m59yvnXPjnHNznHPzmxmzwDmX45zL6dWrV3uXKCJNpCZ2Ij25s0IhgngVCvuAAU0epzVsE5EwMymzfr2CT32FiOBVKKwBhprZYDOLA24Hlrb2xWY2zcwWVFToVoAiXpuYkcyJU7Vs3K++QiRoj1NSXwFWAsPMrMTM7nHO1QJzgXeATcDvnXMbWvuezrllzrnZiYmJwSlaRFptkv/+CroOUiQI+j2anXMzmtm+AlgR7M8XkeDq3T2BjF5dWLXjCLOvzPS6HLlEIdVoFpHwNLFhvUKtr87rUuQShWUoqKcgElomZSRTebqW9eorhL2wDAX1FERCy4SMJEDrFSJBWIaCiISW3t0SGNK7KyuLFQrhLixDQdNHIqFnYkYS+buOcEZ9hbAWlqGg6SOR0DMpI4WTNT7W7dOXtXAWlqEgIqFHfYXIoFAQkYBI6RrPZX3UVwh3CgURCZhJGcnk7zqqvkIYC8tQUKNZJDRNzEim+oyPopJjXpciFyksQ0GNZpHQNKHxOkiaQgpbYRkKIhKakrrEMbxvN1btOPdmixIuFAoiElATM5LJ332E07U+r0uRi6BQEJGAmpiRzKkzdRSVqOcXjsIyFNRoFgldEzOSMFNfIVyFZSio0SwSupas2cuAnmfftzmvuJz5HxR7WJW0VliGgoiErqy0REqPn2LNzvq+Ql5xOXMXryUrTV/iwoFCQUQCKjczhfu/MoQzdY5HX1/H3MVrmTczm9zMFK9Lk1ZQKIhIwH37i+nERBmvF+5j1oSBCoQwolAQkYBbv6+CuJj6Xy+/+3gXecXlHlckraVQEJGAauwh/M+d47isT1cSYqJ44OVCBUOYCMtQ0CmpIqGrqKSCeTOz+fLQXjx202jKT9Zw5WW9tG4hTIRlKOiUVJHQNeeqTH8PYUJGMrdk92fFugN8bUQfjyuT1gjLUBCR8PHodSNIiI3mJ0vX45zzuhy5AIWCiARVr27x/HDyMD7efpg3iw54XY5cgEJBRIJu1oRBjO7fncfe3MiJU2e8LkdaoFAQkaCLjjIeu2k0ZZWn+a+/bPO6HGmBQkFE2kX2wJ7cfsVAFubtYvPB416XI81oVSiYWY6ZvWFmhWZWZGbrzKwo2MWJSGT558nD6J4Qw4/fWE9dnZrOoai1RwovA78DbgWmATc0/Cki0mo9u8TxyNTh5O8+yh8KS7wuR86jtaFQ5pxb6pzb6Zzb3fgT1MpaoMVrIuHrtnEDGDuwB0+8tZmKKjWdQ01rQ+EnZvasmc0ws1saf4JaWQu0eE0kfEVFGY/dPJqjVTX88t3NXpcj54hp5bi7geFALFDXsM0BrwejKBGJbKP6JfKtSem8sHIX38wZQFZaD69LkgatPVK4wjmX45y7yzl3d8PPd4JamYhEtO9fexmdY6N5eMmn+Jo0nXWXNm+1NhTyzGxkUCsRkQ6le0Is385NZ0f5SR5fvhFAd2kLAa2dPpoIfGpmO4HTgAHOOZcVtMpEJOL9YPIw3ttSyu8+3oWZ8cbafbpLm8daGwpTglqFiHRIZsZvZmQz+Vcf8txHO5n7lUwFgsdaFQpenn4qIpGt9MRpEmKjOVnj49mPdpI7JEXB4CFd5kJEPNPYQ/jtXTncMXEgp87UMfvFAt2lzUMKBRHxTONd2nIzU/g/N4wie2APan11vL+51OvSOiyFgoh4puld2uJionh61li6xMfw/pYyKk/Xelxdx6RQEJGQkZrYid/MzGZHWSX//NpnulObB8IyFHTtI5HIlZuZwo+mDGfFuoM8+/edXpfT4YRlKOjaRyKRbfaVGUwd3Zcn3t7MyuLDXpfToYRlKIhIZDMzfnnb5aQnd+bBVwo5WHHK65I6DIWCiISkrvEx/M+d46iu8XH/ywXU1NZd+EVyyRQKIhKyhvTuxpPTL6dwzzF+1nB9JAkuhYKIhLTrs1IZn96TF1fu5vUmd2vT1VSDQ6EgIiHvwa8OJSbK+NEfiti4/7iuphpEFs7nAefk5Lj8/HyvyxCRdvDWugPcv7iQbvExRJnx9B1jdY2ki2RmBc65nPM9pyMFEQkLU8ekMn1cGsdP1VLjq6NLXGsv8ixtoVAQkbCQV1zOXzeVMnPCQE6d8TH9mTyWFx3wuqyIo1AQkZDX2EOYNzObf//GGJ6eNRYHPLC4kHnvbdPlMAJIoSAiIa/p1VQBpoxO5dm7chiV2o3/eHcr3//9Z5yu9XlcZWTQpJyIhLw5V2V+btvVw3pz1WW9mPfedv7fn7ey90gV/3PnOJK7xntQYeTQkYKIhC0z48GvDmXezGzW7avg5qc/ZuuhE16XFdYUCiIS9m7I6ser351EdU0dN/z6o88tatNCt9ZTKIhIRPjCgB78ae4X6dM9nife2sxPl24A0EK3NgqZnoKZZQD/CiQ656Z7XY+IhJ/+PTrx1sNXcuezq1mYt4u1e46y92j1WU1qaVlQjxTM7HkzKzWz9edsn2JmW8xsu5k9AuCc2+GcuyeY9YhI5OsaH8Nr9+WS1T+Rz0oqmJSRrEBog2BPHy0EpjTdYGbRwFPAVGAkMMPMRga5DhHpQFbvPMzeo1Ukd4njrfUHeH/zIa9LChtBDQXn3IfAkXM2jwe2NxwZ1ABLgJuCWYeIdByNPYSnZo1l/p3jqHNw38uF5BWXe11aWPCi0dwf2NvkcQnQ38ySzWw+kG1mjzb3YjObbWb5ZpZfVlYW7FpFJMw0Xeh2RXoSt45N44yvjvc3l3pdWlgImUazc+4wMKcV4xYAC6D+KqnBrktEwsu5C90evW44f954kA37j+Ocw8w8qiw8eHGksA8Y0ORxWsM2EZGAS+kazw+nDCev+DBLP9vvdTkhz4tQWAMMNbPBZhYH3A4sbcsbmNk0M1tQUVERlAJFJLLMHD+QrLREHl++iROnznhdTkgL9imprwArgWFmVmJm9zjnaoG5wDvAJuD3zrkNbXlf59wy59zsxEQtRhGRC4uOMh67aTRllaf51Z+3eV1OSAtqT8E5N6OZ7SuAFcH8bBGRpi4f0IOZ4weyMG8n08elMbJfd69LCkm6zIWIdBg/nDyMHp3j+Lc/raeuTuepnE9YhoJ6CiJyMXp0juORqcMp2H2U1wpLvC4nJIVlKKinICIXa/rYNMYN6skTb23mWFWN1+WEnLAMBRGRixUVZfzs5tFUVJ/hyXe2eF1OyFEoiEiHMyK1O3dNSueVT/bw2d5jXpcTUsIyFNRTEJFL9b2vD6VX13h+/Mf1+NR09gvLUFBPQUQuVbeEWCZmJLFuXwWLP9nj397R79IWlqEgIhIIt18xkJgo4+fLN1JeeVp3aUOhICIdWO6QFJ64ZQxVZ+qY9dtVzF28tsPfpS0sQ0E9BREJlOk5AxifnsSWQ5UM69OtQwcChGkoqKcgIoGSV1zO9tJKhvXpysodh3l8+UavS/JUWIaCiEggNPYQ5s3KZtmDXyYrLZHf/n0nv3mv4140T6EgIh1W07u0xcVE8cq9E8lM6cJ//WUba3adeyfhjkGhICId1pyrMs/qIXSJj+H3cyYxKKkz9yxcw5aDJzyszhsKBRGRJpK7xvPCd8bTKS6abz2/mpKjVV6X1K7CMhR09pGIBNOApM688J3xVNX4+Nbzn3DkZMe5cF5YhoLOPhKRYBvetzvP3XUFJUeruXvhGqpqar0uqV2EZSiIiLSH8YOT+M2MbNaVHOO+RYWc8dV5XVLQKRRERFoweVRfHv/GGD7YWsbdv1tz1h3bIvE6SQoFEZELmDF+ILeNS+Oj7eU8tGQtQMReJynG6wJERMLBk9OzqKg+w5tFByg/sZKtpZUReZ2ksDxS0NlHItLezIxn7hjHsD5dWbXzCEld4rg8rYfXZQVcWIaCzj4SES+s3nmYssoacjOT2V5aybW/+oDiskqvywqosAwFEZH25r9O0sxsFt87kX+5bjj7j53i+l//nbfXH/S6vIBRKIiItELT6yQBzL4yk/+ekU3PznHMWVTAL97eTG0EnLJqzoXvvUlzcnJcfn6+12WISAd2utbH/122kcWr9/DFIcn8+vZskrvGe11Wi8yswDmXc77ndKQgInIJ4mOi+fdvjOHJ6Vms2XWUab/5iE/3HvO6rIumUBARCYBv5gzg9ftyiYoybn06j8fe3EjTmZjmFrrN/6CYvOLys7Z5uShOoSAiEiCj+yeybO6XGNW/O899tJO7f/cJe49UsfTTfdy/qJB+iQmUHK0666dfYgL3Lypk2Wf7cc55vihOPQURkQDz1Tl+8L+f8sba/W16XW5mMpsPngj6oriWegphuaLZzKYB04YMGeJ1KSIinxMdZfzqn7KJiY7if/NL+OqI3kwe1bfF1zz59mbyig/z0DVDPF0lHZah4JxbBizLycm51+taRETOJ6+4nL9uKuWha4awaPUe7vnS4GZ/2ecVl1NV4wPghZW7mZiZ7FkwqKcgIhJgTRe6ff/aYcybmc3cxWs/11BuOvaX07Mwg6+P6NPs2PagUBARCbBzF7rlZqYwb2Y2RSWfv15b49jrs/pxRXoSRfuONTu2PajRLCISIl7I28VPlm7gz9+7kqF9ugXtc7R4TUQkDEwd3RczWL7ugGc1KBREREJE7+4JXJGexPIihYKIiAA3ZKWyrbSSrYdOePL5CgURkRAypXEKyaOjBYWCiEgI6d0tgfHpSZ71FRQKIiIh5oasVLZ7NIWkUBARCTGTR/clyuBND6aQwjIUzGyamS2oqPBmcYeISDD17pbA+MFJLC/aT3uvJQvLUHDOLXPOzU5M9ObSsiIiwXZ9Vj+Ky06y9VBlu35uWIaCiEikmzKqfgppeVHbLr99qRQKIiIhqFe3eCYMTubNdQfadQpJoSAiEqKuz0plR9lJtrTjWUgKBRGREDVldOMUUvudhaRQEBEJUSld45mYkczyovabQlIoiIiEsOuzUtlRfpLNB9tnCkmhICISwiaPat8pJIWCiEgIS+kaz6TMZJa301lICgURkRB3/Zh+7Cw/yaYDwZ9CUiiIiIS4yaP6EB1lLF8X/IVsCgURkRCX3DWeSe10FpJCQUQkDFw3JpVdh6vYeOB4UD9HoSAiEgb8U0hBPgtJoSAiEgaSu8aT2w5nIYVMKJhZFzN7wcx+a2azvK5HRCTUXDcmld2Hq9iwP3hTSEENBTN73sxKzWz9OdunmNkWM9tuZo80bL4FeM05dy9wYzDrEhEJRwcqTtUvZGty/+a84nLmf1AcsM8I9pHCQmBK0w1mFg08BUwFRgIzzGwkkAbsbRjmC3JdIiJhZ2JGElFRxh8KSnDOkVdcztzFa8lKC9wNx4IaCs65D4Ej52weD2x3zu1wztUAS4CbgBLqgyHodYmIhKPczBTuzk2n9MRpHn19HXMXr2XezGxyM1MC9hle/PLtzz+OCKA+DPoDrwO3mtkzwLLmXmxms80s38zyy8rKglupiEiIuf/qIXSKjWLJmr3cMWFgQAMBICag73YJnHMngbtbMW4BsAAgJyenfe9oLSLisU0Hj9MpNoZ7vzyQRav3MDEzOeyPFPYBA5o8TmvYJiIiLWjsIcyblc33rx3GvJnZzF28lrzi8oB9hhehsAYYamaDzSwOuB1Y2pY3MLNpZragoqIiKAWKiISiopKKs3oIuZkpzJuZTVFJ4H4XWjAXQZjZK8DVQApwCPiJc+45M7sO+C8gGnjeOff4xbx/Tk6Oy8/PD1C1IiIdg5kVOOdyzvdcUHsKzrkZzWxfAawI5meLiEjb6dRPERHxC8tQUE9BRCQ4wjIUnHPLnHOzExMDt4pPRETCNBRERCQ4gnr2UbCZWRmwu5XDE4ELzTddaExLzzf3XAoQuJOIg6M1/25C4TMu5j3a8hrtIy0L9n6ifaTl5wK5nwxyzvU67zPOuQ7xAyy41DEtPd/cc0C+13/3QPy7CYXPuJj3aMtrtI94u59oH7ngc+2yn3Sk6aNmr6fUhjEtPd+a9w9V7VF7ID7jYt6jLa/RPtKyYNevfSQE9pGwnj4KB2aW75pZJCIC2kekddprP+lIRwpeWeB1ARLytI9Ia7TLfqIjBRER8dORgoiI+CkURETET6EgIiJ+CgUPmVmGmT1nZq95XYuEDjPrYmYvmNlvzWyW1/VI6Anm7w6FwkUys+fNrNTM1p+zfYqZbTGz7Wb2SEvv4Zzb4Zy7J7iVSiho4/5yC/Cac+5e4MZ2L1Y80ZZ9JJi/OxQKF28hMKXpBjOLBp4CpgIjgRlmNtLMxpjZm+f89G7/ksVDC2nl/kL9LWr3NgzztWON4q2FtH4fCZqg3mQnkjnnPjSz9HM2jwe2O+d2AJjZEuAm59zPgRvauUQJIW3ZX4AS6oPhU/TFrcNo4z6yMVh1aIcLrP784xse1P/P3b+5wWaWbGbzgWwzezTYxUnIaW5/eR241cyeIQQueyCeOu8+EszfHTpS8JBz7jAwx+s6JLQ4504Cd3tdh4SuYP7u0JFCYO0DBjR5nNawTeR8tL/IhbT7PqJQCKw1wFAzG2xmccDtwFKPa5LQpf1FLqTd9xGFwkUys1eAlcAwMysxs3ucc7XAXOAdYBPwe+fcBi/rlNCg/UUuJFT2EV0QT0RE/HSkICIifgoFERHxUyiIiIifQkFERPwUCiIi4qdQEBERP4WCSBCZ2U/N7Ade1yHSWgoFERHxUyiIBJiZ/auZbTWzj4BhXtcj0ha6SqpIAJnZOOqvT/MF6v//KgQKvKxJpC0UCiKB9WXgDedcFYCZ6QJ3ElY0fSQiIn4KBZHA+hC42cw6mVk3YJrXBYm0haaPRALIOVdoZq8CnwGl1F8PXyRs6NLZIiLip+kjERHxUyiIiIifQkFERPwUCiIi4qdQEBERP4WCiIj4KRRERMRPoSAiIn7/H4FgErsy5FcYAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "mdim, cdim, m,d = mesh_dim(o[200:], upper_size_ratio=1.0, lower_size_ratio=0.0)\n",
    "dcrit = mesh_find_target_d(o)\n",
    "\n",
    "plt.loglog(d,m,'x-')\n",
    "plt.xlabel('d')\n",
    "plt.ylabel('m')\n",
    "\n",
    "print(mdim)\n",
    "print(cdim)\n",
    "print(dcrit)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: \u001b[33mWARN: Box bound precision lowered by casting to float32\u001b[0m\n",
      "  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))\n"
     ]
    }
   ],
   "source": [
    "new_agent = ARSZooAgent(env_name, algo, seed=0, n_workers=8, n_delta=64, postprocessor=mdim_div_stable, step_schedule=[0.05, 0.005],  exp_schedule=[0.05, 0.005])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "env, old_model = load_zoo_agent(env_name, algo)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'new_agent' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-18-0b46e9b2b11e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mnew_agent\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlearn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m50\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m;\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mplot\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnew_agent\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mraw_rew_hist\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'new_agent' is not defined"
     ]
    }
   ],
   "source": [
    "new_agent.learn(50);\n",
    "plt.plot(new_agent.raw_rew_hist)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "mesh dimension\n",
      "[1.65165222 1.50077426 1.47188814 1.43729194 1.4891903  1.51134688\n",
      " 1.55907226 1.51392266 1.69615533 1.54201792]\n",
      "mean: 1.537331191504856, std: 0.07612935573121957\n",
      "rewards\n",
      "[27.29775238 26.79888535 26.62466812 26.59468842 26.71964455 27.29981232\n",
      " 27.79039383 27.31723595 27.36193085 27.00781059]\n",
      "mean: 27.081282234191896, std: 0.37324116445731953\n",
      "\n",
      "\n",
      "mesh dimension\n",
      "[1.04105945 1.12599638 1.17756477 1.1979042  1.0433496  1.21110457\n",
      " 1.03676292 1.09788625 1.22385127 1.1741975 ]\n",
      "mean: 1.132967691385411, std: 0.07020251916917747\n",
      "rewards\n",
      "[22.59495735 23.33088684 23.11067581 23.89262772 21.7189064  23.01237869\n",
      " 22.86103821 22.09728622 23.60745621 22.56051445]\n",
      "mean: 22.878672790527343, std: 0.6303239861898635\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "model_list = [old_model, new_agent.model]\n",
    "num_runs = 10\n",
    "\n",
    "for model in model_list:\n",
    "    mdims = xr.DataArray(np.zeros((num_runs)))\n",
    "    rews =  xr.DataArray(np.zeros((num_runs)))\n",
    "\n",
    "    for j in range(num_runs):\n",
    "        o,a,r,l = do_rollout_stable(env, model)\n",
    "        o_norm = env.normalize_obs(o).squeeze()\n",
    "        o_norm  = o_norm[200:]\n",
    "        rews[j] = np.sum(r)\n",
    "        try:\n",
    "            mdims[j], _, _, _ = mesh_dim(o_norm)\n",
    "        except:\n",
    "            mdims[j] = np.nan\n",
    "    print(\"mesh dimension\")\n",
    "    print(mdims.data)\n",
    "    mean = mdims.mean().item()\n",
    "    std = mdims.std().item()\n",
    "    print(f\"mean: {mean}, std: {std}\")\n",
    "\n",
    "    print(\"rewards\")\n",
    "    print(rews.data)\n",
    "    mean = rews.mean().item()\n",
    "    std = rews.std().item()\n",
    "    print(f\"mean: {mean}, std: {std}\")\n",
    "    print();print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-08-29 02:20:20,584\tINFO services.py:1269 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "2021-08-29 02:20:22,149\tWARNING function_runner.py:545 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.\n",
      "2021-08-29 02:20:22,174\tWARNING tune.py:494 -- Tune detects GPUs, but no trials are using GPUs. To enable trials to use GPUs, set tune.run(resources_per_trial={'gpu': 1}...) which allows Tune to expose 1 GPU to each trial. You can also override `Trainable.default_resource_request` if using the Trainable API.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 19.1/62.9 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 1.0/24 CPUs, 0/1 GPUs, 0.0/27.86 GiB heap, 0.0/13.93 GiB objects (0.0/1.0 accelerator_type:RTX)<br>Result logdir: /home/sgillen/ray_results/training_function_2021-08-29_02-20-22<br>Number of trials: 12/12 (11 PENDING, 1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                   </th><th>status  </th><th>loc  </th><th>algo  </th><th>env_name               </th><th>train  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>training_function_55f9f_00000</td><td>RUNNING </td><td>     </td><td>ppo   </td><td>Walker2DBulletEnv-v0   </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00001</td><td>PENDING </td><td>     </td><td>a2c   </td><td>Walker2DBulletEnv-v0   </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00002</td><td>PENDING </td><td>     </td><td>ppo   </td><td>HalfCheetahBulletEnv-v0</td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00003</td><td>PENDING </td><td>     </td><td>a2c   </td><td>HalfCheetahBulletEnv-v0</td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00004</td><td>PENDING </td><td>     </td><td>ppo   </td><td>HopperBulletEnv-v0     </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00005</td><td>PENDING </td><td>     </td><td>a2c   </td><td>HopperBulletEnv-v0     </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00006</td><td>PENDING </td><td>     </td><td>ppo   </td><td>Walker2DBulletEnv-v0   </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00007</td><td>PENDING </td><td>     </td><td>a2c   </td><td>Walker2DBulletEnv-v0   </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00008</td><td>PENDING </td><td>     </td><td>ppo   </td><td>HalfCheetahBulletEnv-v0</td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00009</td><td>PENDING </td><td>     </td><td>a2c   </td><td>HalfCheetahBulletEnv-v0</td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00010</td><td>PENDING </td><td>     </td><td>ppo   </td><td>HopperBulletEnv-v0     </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00011</td><td>PENDING </td><td>     </td><td>a2c   </td><td>HopperBulletEnv-v0     </td><td>True   </td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m 2021-08-29 02:20:22,693\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13558)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m 2021-08-29 02:20:22,720\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13557)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m 2021-08-29 02:20:22,736\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13554)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m 2021-08-29 02:20:22,789\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13547)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m 2021-08-29 02:20:22,739\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13582)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m 2021-08-29 02:20:22,756\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13549)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m 2021-08-29 02:20:22,766\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13586)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m 2021-08-29 02:20:22,788\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13556)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m 2021-08-29 02:20:22,791\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13559)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m 2021-08-29 02:20:22,802\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13552)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m 2021-08-29 02:20:22,829\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13555)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m 2021-08-29 02:20:22,813\tERROR function_runner.py:254 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 267, in run\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     self._status_reporter.get_checkpoint())\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m   File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m NameError: name 'load_zoo_agent' is not defined\n",
      "\u001b[2m\u001b[36m(pid=13553)\u001b[0m \n",
      "2021-08-29 02:20:22,869\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13558, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13558, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,894\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00008: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13557, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13557, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,907\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00004: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13554, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13554, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,914\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00006: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13582, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13582, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,934\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00002: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13552, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13552, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,937\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00005: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13549, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13549, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,942\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00007: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13586, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13586, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,961\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00001: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13556, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13556, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,964\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00010: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13559, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13559, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,967\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00011: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13547, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13547, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:22,992\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00003: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13553, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13553, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n",
      "2021-08-29 02:20:23,002\tERROR trial_runner.py:732 -- Trial training_function_55f9f_00009: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 702, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 686, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/worker.py\", line 1481, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13555, ip=128.111.57.96)\n",
      "  File \"python/ray/_raylet.pyx\", line 505, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 449, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/_private/function_manager.py\", line 556, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 173, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/trainable.py\", line 232, in train\n",
      "    result = self.step()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 366, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 513, in _report_thread_runner_error\n",
      "    (\"Trial raised an exception. Traceback:\\n{}\".format(err_tb_str)\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=13555, ip=128.111.57.96)\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 248, in run\n",
      "    self._entrypoint()\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 316, in entrypoint\n",
      "    self._status_reporter.get_checkpoint())\n",
      "  File \"/home/sgillen/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/function_runner.py\", line 580, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-2-761a5f48f0d3>\", line 7, in training_function\n",
      "NameError: name 'load_zoo_agent' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for training_function_55f9f_00000:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00008:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00004:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00006:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00002:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00005:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00007:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00001:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00010:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00011:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00003:\n",
      "  {}\n",
      "  \n",
      "Result for training_function_55f9f_00009:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 19.5/62.9 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 0/24 CPUs, 0/1 GPUs, 0.0/27.86 GiB heap, 0.0/13.93 GiB objects (0.0/1.0 accelerator_type:RTX)<br>Result logdir: /home/sgillen/ray_results/training_function_2021-08-29_02-20-22<br>Number of trials: 12/12 (12 ERROR)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                   </th><th>status  </th><th>loc  </th><th>algo  </th><th>env_name               </th><th>train  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>training_function_55f9f_00000</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>Walker2DBulletEnv-v0   </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00001</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>Walker2DBulletEnv-v0   </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00002</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>HalfCheetahBulletEnv-v0</td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00003</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>HalfCheetahBulletEnv-v0</td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00004</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>HopperBulletEnv-v0     </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00005</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>HopperBulletEnv-v0     </td><td>False  </td></tr>\n",
       "<tr><td>training_function_55f9f_00006</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>Walker2DBulletEnv-v0   </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00007</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>Walker2DBulletEnv-v0   </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00008</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>HalfCheetahBulletEnv-v0</td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00009</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>HalfCheetahBulletEnv-v0</td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00010</td><td>ERROR   </td><td>     </td><td>ppo   </td><td>HopperBulletEnv-v0     </td><td>True   </td></tr>\n",
       "<tr><td>training_function_55f9f_00011</td><td>ERROR   </td><td>     </td><td>a2c   </td><td>HopperBulletEnv-v0     </td><td>True   </td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 12<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                   </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                                         </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>training_function_55f9f_00000</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00000_0_algo=ppo,env_name=Walker2DBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt   </td></tr>\n",
       "<tr><td>training_function_55f9f_00001</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00001_1_algo=a2c,env_name=Walker2DBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt   </td></tr>\n",
       "<tr><td>training_function_55f9f_00002</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00002_2_algo=ppo,env_name=HalfCheetahBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt</td></tr>\n",
       "<tr><td>training_function_55f9f_00003</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00003_3_algo=a2c,env_name=HalfCheetahBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt</td></tr>\n",
       "<tr><td>training_function_55f9f_00004</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00004_4_algo=ppo,env_name=HopperBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt     </td></tr>\n",
       "<tr><td>training_function_55f9f_00005</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00005_5_algo=a2c,env_name=HopperBulletEnv-v0,train=False_2021-08-29_02-20-22/error.txt     </td></tr>\n",
       "<tr><td>training_function_55f9f_00006</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00006_6_algo=ppo,env_name=Walker2DBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt    </td></tr>\n",
       "<tr><td>training_function_55f9f_00007</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00007_7_algo=a2c,env_name=Walker2DBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt    </td></tr>\n",
       "<tr><td>training_function_55f9f_00008</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00008_8_algo=ppo,env_name=HalfCheetahBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt </td></tr>\n",
       "<tr><td>training_function_55f9f_00009</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00009_9_algo=a2c,env_name=HalfCheetahBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt </td></tr>\n",
       "<tr><td>training_function_55f9f_00010</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00010_10_algo=ppo,env_name=HopperBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt     </td></tr>\n",
       "<tr><td>training_function_55f9f_00011</td><td style=\"text-align: right;\">           1</td><td>/home/sgillen/ray_results/training_function_2021-08-29_02-20-22/training_function_55f9f_00011_11_algo=a2c,env_name=HopperBulletEnv-v0,train=True_2021-08-29_02-20-22/error.txt     </td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [training_function_55f9f_00000, training_function_55f9f_00001, training_function_55f9f_00002, training_function_55f9f_00003, training_function_55f9f_00004, training_function_55f9f_00005, training_function_55f9f_00006, training_function_55f9f_00007, training_function_55f9f_00008, training_function_55f9f_00009, training_function_55f9f_00010, training_function_55f9f_00011])",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-761a5f48f0d3>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     29\u001b[0m         \u001b[0;34m\"train\"\u001b[0m \u001b[0;34m:\u001b[0m \u001b[0mtune\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgrid_search\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     30\u001b[0m         \u001b[0;34m\"env_name\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mtune\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgrid_search\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Walker2DBulletEnv-v0\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\"HalfCheetahBulletEnv-v0\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\"HopperBulletEnv-v0\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 31\u001b[0;31m         \u001b[0;34m\"algo\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mtune\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgrid_search\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'ppo'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'a2c'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     32\u001b[0m     })\n\u001b[1;32m     33\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/baselines/lib/python3.6/site-packages/ray/tune/tune.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, loggers, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint, _remote)\u001b[0m\n\u001b[1;32m    541\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    542\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mstate\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0msignal\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSIGINT\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 543\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    544\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    545\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete: %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTuneError\u001b[0m: ('Trials did not complete', [training_function_55f9f_00000, training_function_55f9f_00001, training_function_55f9f_00002, training_function_55f9f_00003, training_function_55f9f_00004, training_function_55f9f_00005, training_function_55f9f_00006, training_function_55f9f_00007, training_function_55f9f_00008, training_function_55f9f_00009, training_function_55f9f_00010, training_function_55f9f_00011])"
     ]
    }
   ],
   "source": [
    "from ray import tune\n",
    "\n",
    "def training_function(config):\n",
    "    import pybullet_envs\n",
    "\n",
    "    train, env_name, algo = config[\"train\"], config[\"env_name\"], config[\"algo\"]\n",
    "    env, model = load_zoo_agent(env_name, algo)\n",
    "    \n",
    "    if train:\n",
    "        new_agent = ARSZooAgent(env_name, algo, n_workers=24, n_delta=64, postprocessor=mdim_div_stable, step_schedule=[0.05, 0.005],  exp_schedule=[0.05, 0.005])\n",
    "        new_agent.learn(100) \n",
    "    \n",
    "    o,a,r,l = do_rollout_stable(env, model)\n",
    "    o_norm = env.normalize_obs(o).squeeze()\n",
    "    o_norm  = o_norm[200:]\n",
    "    rew = np.sum(r)\n",
    "    \n",
    "    try:\n",
    "        mdim, _, _, _ = mesh_dim(o_norm)\n",
    "    except:\n",
    "        mdim = np.nan\n",
    "\n",
    "    tune.report(mdim=mdim, reward=rew)\n",
    "\n",
    "\n",
    "analysis = tune.run(\n",
    "    training_function,\n",
    "    config={\n",
    "        \"train\" : tune.grid_search([False, True]),\n",
    "        \"env_name\": tune.grid_search([\"Walker2DBulletEnv-v0\",\"HalfCheetahBulletEnv-v0\",\"HopperBulletEnv-v0\"]),\n",
    "        \"algo\": tune.grid_search(['ppo', 'a2c'])\n",
    "    })\n",
    "\n",
    "print(\"Best config: \", analysis.get_best_config(\n",
    "    metric=\"mdim\", mode=\"min\"))\n",
    "\n",
    "# Get a dataframe for analyzing trial results.\n",
    "df = analysis.results_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "rd = analysis.results_df.to_csv('test.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'trial_id,mdim,reward,time_this_iter_s,done,timesteps_total,episodes_total,training_iteration,experiment_id,date,timestamp,time_total_s,pid,hostname,node_ip,time_since_restore,timesteps_since_restore,iterations_since_restore,experiment_tag,config.train,config.env_name,config.algo\\n5f944_00000,1.662833423343824,33.140342712402344,1.1313729286193848,True,,,1,efd44a352c0e4c329aa167aeb426124a,2021-08-29_01-52-02,1630227122,1.1313729286193848,3989,sguc2,128.111.57.96,1.1313729286193848,0,1,\"0_algo=ppo,env_name=Walker2DBulletEnv-v0,train=False\",False,Walker2DBulletEnv-v0,ppo\\n5f944_00001,,3.2583043575286865,0.13784122467041016,True,,,1,f626496cbc8844ec83297e7b39a95d1b,2021-08-29_01-52-01,1630227121,0.13784122467041016,3986,sguc2,128.111.57.96,0.13784122467041016,0,1,\"1_algo=a2c,env_name=Walker2DBulletEnv-v0,train=False\",False,Walker2DBulletEnv-v0,a2c\\n5f944_00002,1.651652224696957,27.297752380371094,1.145392894744873,True,,,1,c68871ecf92c4a8d926fef7de6a7d408,2021-08-29_01-52-02,1630227122,1.145392894744873,3999,sguc2,128.111.57.96,1.145392894744873,0,1,\"2_algo=ppo,env_name=HalfCheetahBulletEnv-v0,train=False\",False,HalfCheetahBulletEnv-v0,ppo\\n5f944_00003,1.6107201530829376,32.872032165527344,1.1958355903625488,True,,,1,d8b65ed2a5d249bd8ac5a7118471d57f,2021-08-29_01-52-03,1630227123,1.1958355903625488,3984,sguc2,128.111.57.96,1.1958355903625488,0,1,\"3_algo=a2c,env_name=HalfCheetahBulletEnv-v0,train=False\",False,HalfCheetahBulletEnv-v0,a2c\\n5f944_00004,1.5108682475970283,30.000423431396484,0.9771959781646729,True,,,1,10e9a28b84ad4cea8744a0b0bb2d0758,2021-08-29_01-52-02,1630227122,0.9771959781646729,3997,sguc2,128.111.57.96,0.9771959781646729,0,1,\"4_algo=ppo,env_name=HopperBulletEnv-v0,train=False\",False,HopperBulletEnv-v0,ppo\\n5f944_00005,0.8398481810348197,23.638809204101562,0.9235587120056152,True,,,1,37f0e3ae20ef4c68b84df9611802b5c1,2021-08-29_01-52-02,1630227122,0.9235587120056152,3979,sguc2,128.111.57.96,0.9235587120056152,0,1,\"5_algo=a2c,env_name=HopperBulletEnv-v0,train=False\",False,HopperBulletEnv-v0,a2c\\n5f944_00006,1.662833423343824,33.140342712402344,1.162675380706787,True,,,1,7d57844cb49b43438030217ad0dc0276,2021-08-29_01-52-02,1630227122,1.162675380706787,3987,sguc2,128.111.57.96,1.162675380706787,0,1,\"6_algo=ppo,env_name=Walker2DBulletEnv-v0,train=True\",True,Walker2DBulletEnv-v0,ppo\\n5f944_00007,,3.2583043575286865,0.19421648979187012,True,,,1,a425d2c6a78e4b2ebcc3987cca149705,2021-08-29_01-52-01,1630227121,0.19421648979187012,3981,sguc2,128.111.57.96,0.19421648979187012,0,1,\"7_algo=a2c,env_name=Walker2DBulletEnv-v0,train=True\",True,Walker2DBulletEnv-v0,a2c\\n5f944_00008,1.651652224696957,27.297752380371094,1.1691322326660156,True,,,1,e0bc9d9944f442289f3b904523920443,2021-08-29_01-52-02,1630227122,1.1691322326660156,3973,sguc2,128.111.57.96,1.1691322326660156,0,1,\"8_algo=ppo,env_name=HalfCheetahBulletEnv-v0,train=True\",True,HalfCheetahBulletEnv-v0,ppo\\n5f944_00009,1.6107201530829376,32.872032165527344,1.1936323642730713,True,,,1,d949752656d44a75a72bccb0298910aa,2021-08-29_01-52-02,1630227122,1.1936323642730713,3983,sguc2,128.111.57.96,1.1936323642730713,0,1,\"9_algo=a2c,env_name=HalfCheetahBulletEnv-v0,train=True\",True,HalfCheetahBulletEnv-v0,a2c\\n5f944_00010,1.5108682475970283,30.000423431396484,1.0029053688049316,True,,,1,e7b6be7a761040c6a1e2470af1d09fab,2021-08-29_01-52-02,1630227122,1.0029053688049316,3970,sguc2,128.111.57.96,1.0029053688049316,0,1,\"10_algo=ppo,env_name=HopperBulletEnv-v0,train=True\",True,HopperBulletEnv-v0,ppo\\n5f944_00011,0.8398481810348197,23.638809204101562,0.9461500644683838,True,,,1,5eb8457380334476b5aa84cab4d7120a,2021-08-29_01-52-02,1630227122,0.9461500644683838,3982,sguc2,128.111.57.96,0.9461500644683838,0,1,\"11_algo=a2c,env_name=HopperBulletEnv-v0,train=True\",True,HopperBulletEnv-v0,a2c\\n'"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'df' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-00cf07b74dcd>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mdf\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m: name 'df' is not defined"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Mujoco 1.5",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
